version: '3.7'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.mssql
    volumes:
      - ./backup:/backup
    networks:
      - default
  backup:
    build:
      context: ../
    volumes:
      - ./backup:/backup
      - ./remote:/remote
      - ../backup.sh:/usr/local/bin/backup.sh
    environment:
      - TZ
      - DB_SERVER
      - DB_USER
      - DB_PASSWORD
      - DB_NAMES
      - CRON_SCHEDULE
      - BACKUP_CLEANUP
      - BACKUP_AGE
      - SKIP_BACKUP_LOG
      - PACK
      - ZIP_PASSWORD
      - PUSH_REMOTE_MODE
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_AUTH
      - SMTP_USER
      - SMTP_PASS
      - SMTP_FROM
      - SMTP_TLS
      - MAIL_TO
    networks:
      - default