version: '3.7'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.mssql
    volumes:
      - ./backup/tmp:/backup_tmp
      - ./backup:/backup
    networks:
      - default
  backup:
    build:
      context: ../
    volumes:
      - ./backup/tmp:/backup_tmp
      - ./backup:/backup
      - ../backup.sh:/usr/local/bin/backup.sh
    environment:
      - TZ=Europe/Berlin
      - DB_SERVER=db
      - DB_USER=SA
      - DB_PASSWORD=MySqlServerPassword1234
      - "DB_NAMES=AdventureWorks2019"
      - CRON_SCHEDULE=0 1 * * *
    networks:
      - default